---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    ksonnet.io/component: minio
  name: dkube-minio-pvc
  namespace: dkube-infra
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 75Gi
  storageClassName: ""
  volumeName: dkube-minio-pv
---
apiVersion: v1
kind: Service
metadata:
  name: dkube-minio-server
  namespace: dkube-infra
spec:
  ports:
  - nodePort: 32223
    port: 9000
    protocol: TCP
    targetPort: 9000
  selector:
    app: minio
  type: NodePort
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: dkube-minio-server
  namespace: dkube
spec:
  hosts:
  - "*"
  gateways:
  - dkube-istio-gateway
  http:
  - match:
    - uri:
        prefix: /minio/
    rewrite:
        uri: /
    route:
    - destination:
        port:
          number: 9000
        host: dkube-minio-server
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: minio
    ksonnet.io/component: minio
  name: dkube-minio-server
  namespace: dkube-infra
spec:
  replicas: 1
  selector:
    matchLabels:
      app: minio
  template:
    metadata:
      labels:
        app: minio
    spec:
      containers:
      - args:
        - server
        - /storage
        env:
        - name: MINIO_ACCESS_KEY
          value: dkube
        - name: MINIO_SECRET_KEY
          value: minioSecretKey
        image: minioImage
        imagePullPolicy: IfNotPresent
        name: main
        ports:
        - containerPort: 9000
          protocol: TCP
        resources:
          limits:
            memory: 5Gi
        volumeMounts:
        - mountPath: /storage
          name: storage
      dnsConfig:
        options:
        - name: single-request-reopen
        - name: timeout
          value: "30"
      nodeSelector: NODE_SELECTOR
      volumes:
      - name: storage
        persistentVolumeClaim:
          claimName: dkube-minio-pvc
